---
- ふざけんな
- うざい
- きもい
- 調子のんな
- 死ね
- 殺す
- バカ
- アホ
- 死にたい
- ブス
- アメ公
- きちがい
- うせろ
- クソ
- ホモ
- クズ
- 害児
- ばばあ
- じじい
- ハゲ
- おっぱい
- 乳首
- 出っ歯
- ファック
- うんこ
- くたばれ
- 短足
- オナニー
- 包茎
- クンニ
- ちび
- チビ
- ばか
- あほ
